[package]
name = "libtww"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
arrayvec = { version = "0.4.7", default-features = false }
gcn = { git = "https://github.com/CryZe/gcn", rev = "ea0f9ce98789d8e0c21a7e813d9a16ee6235c35d" }
